"use client";
import { useEffect, useState } from "react";
import { useTranslations } from "next-intl";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { toast } from "sonner";

const EVENTS = ["ABSENCE_ALERT", "FEE_REMINDER", "EXAM_RESULT_PUBLISHED", "EMERGENCY_BROADCAST"] as const;
const CHANNELS = ["SMS", "WHATSAPP", "EMAIL", "IN_APP"] as const;
export function NotificationSettingsSection() {
  const t = useTranslations("notifications");
  const [enabled, setEnabled] = useState(false); const [events, setEvents] = useState<Record<string, boolean>>({}); const [channels, setChannels] = useState<string[]>(["IN_APP"]); const [credentials, setCredentials] = useState({ resendApiKey: "", whatsappAccessToken: "", whatsappPhoneNumberId: "", smsApiUrl: "", smsApiKey: "", smsFrom: "" }); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/notifications/settings").then((r) => r.json()).then((r) => { if (r.data) { setEnabled(r.data.enabled); setEvents(r.data.events || {}); setChannels(r.data.channels || ["IN_APP"]); } }).catch(() => undefined); }, []);
  async function save() { setSaving(true); try { const response = await fetch("/api/notifications/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled, events, channels, ...credentials }) }); if (!response.ok) throw new Error(); toast.success(t("settingsSaved")); } catch { toast.error(t("settingsSaveFailed")); } finally { setSaving(false); } }
  return <Card><CardHeader><CardTitle>{t("automationTitle")}</CardTitle><p className="text-sm text-muted-foreground">{t("automationDescription")}</p></CardHeader><CardContent className="space-y-6"><label className="flex items-center gap-3 text-sm font-medium"><Checkbox checked={enabled} onCheckedChange={(value) => setEnabled(value === true)} />{t("automationEnabled")}</label><div className="grid gap-3 sm:grid-cols-2">{EVENTS.map((event) => <label key={event} className="flex items-center gap-3 text-sm"><Checkbox checked={events[event] !== false} onCheckedChange={(value) => setEvents((current) => ({ ...current, [event]: value === true }))} />{t(`events.${event}`)}</label>)}</div><div><p className="mb-3 text-sm font-medium">{t("channels")}</p><div className="flex flex-wrap gap-4">{CHANNELS.map((channel) => <label key={channel} className="flex items-center gap-2 text-sm"><Checkbox checked={channels.includes(channel)} onCheckedChange={(value) => setChannels((current) => value === true ? [...new Set([...current, channel])] : current.filter((item) => item !== channel))} />{channel}</label>)}</div></div><div className="grid gap-3 sm:grid-cols-2"><Input type="password" placeholder="Resend API key" value={credentials.resendApiKey} onChange={(e) => setCredentials((c) => ({ ...c, resendApiKey: e.target.value }))} /><Input placeholder="WhatsApp phone number ID" value={credentials.whatsappPhoneNumberId} onChange={(e) => setCredentials((c) => ({ ...c, whatsappPhoneNumberId: e.target.value }))} /><Input type="password" placeholder="WhatsApp access token" value={credentials.whatsappAccessToken} onChange={(e) => setCredentials((c) => ({ ...c, whatsappAccessToken: e.target.value }))} /><Input placeholder="SMS API URL" value={credentials.smsApiUrl} onChange={(e) => setCredentials((c) => ({ ...c, smsApiUrl: e.target.value }))} /><Input type="password" placeholder="SMS API key" value={credentials.smsApiKey} onChange={(e) => setCredentials((c) => ({ ...c, smsApiKey: e.target.value }))} /><Input placeholder="SMS sender" value={credentials.smsFrom} onChange={(e) => setCredentials((c) => ({ ...c, smsFrom: e.target.value }))} /></div><Button onClick={save} disabled={saving}>{saving ? t("saving") : t("saveSettings")}</Button></CardContent></Card>;
}
