import { ExamPaperStudioModel as ExamPaper } from '@/types/exam-studio';

export const EXAM_TEMPLATES: ExamPaper[] = [
  // 1. SSC / HSC Creative (NCTB Srijonshil)
  {
    id: 'template-bangla-1st-ssc',
    title: '১. সৃজনশীল প্রশ্নপত্র (SSC / HSC Board CQ & MCQ)',
    templateCategory: 'nctb-general',
    header: {
      instituteName: '',
      subInstituteText: '',
      examName: 'বার্ষিক পরীক্ষা / নির্বাচনী পরীক্ষা',
      sessionYear: '২০২৬',
      subjectName: 'বাংলা ১ম পত্র (সৃজনশীল)',
      subjectCode: '১০১',
      gradeClass: 'দশম শ্রেণি',
      timeAllowed: '২ ঘণ্টা ৩০ মিনিট',
      totalMarks: '৭০',
      specialInstructions: '[দ্রষ্টব্য: ডান পাশের সংখ্যা প্রশ্নের পূর্ণমান জ্ঞাপক। ক-বিভাগ থেকে ২টি, খ-বিভাগ থেকে ২টি, গ-বিভাগ থেকে ১টি এবং ঘ-বিভাগ থেকে ১টি করে মোট ৭টি প্রশ্নের উত্তর দাও।]',
      bismillahHeader: false,
      examSet: 'ক-সেট',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'bengali',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'classic-center',
      fontSize: 'md',
      lineSpacing: 'normal',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.08,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'solid',
      showHeaderCutLine: false,
      showOMRGrid: false,
      studentInfoBox: false,
      marksPosition: 'right-bracket',
      numberingStyle: 'bengali',
      showDottedAnswerLines: false,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'bengali',
      marginSize: 'standard',
    },
    sections: [
      {
        sectionId: 'sec-gadya',
        title: 'ক-বিভাগ : গদ্য (সৃজনশীল)',
        subTitle: 'যেকোনো ২টি প্রশ্নের উত্তর দাও',
        marksInstruction: '[২ × ১০ = ২০]',
        questions: [
          {
            id: 'q-bangla-1',
            type: 'cq',
            qNumber: '১',
            stimulus:
              'সুমন সাহেব একজন দানশীল সমাজসেবক। গ্রামের দরিদ্র অনাথ ছেলেমেয়েদের লেখাপড়ার জন্য তিনি একটি আধুনিক বিদ্যালয় স্থাপন করেছেন। সেখানে নিজের অর্থায়নে বিনামূল্যে বই-খাতা ও দুপুরের খাবারের ব্যবস্থা করেন। কিন্তু গ্রামের কতিপয় স্বার্থান্বেষী লোক তার এই নিঃস্বার্থ মহৎ উদ্যোগকে লোক দেখানো বলে অপপ্রচার চালায়। এতে সুমন সাহেব ব্যথিত হলেও লক্ষ্য থেকে একচুলও বিচ্যুত হননি।',
            questionText: 'উদ্দীপকটি পড়ে নিচের প্রশ্নগুলোর উত্তর দাও:',
            marks: 10,
            cognitiveLevel: 'সমন্বিত',
            cqParts: {
              ka: { text: 'মমতাদি কত টাকা মাইনেতে লেখকের বাড়িতে কাজ শুরু করেছিল?', marks: 1 },
              kha: { text: '“কাউকে তোয়াক্কা করত না অথচ সবাই তাকে মান্য করত”—ব্যাখ্যা কর।', marks: 2 },
              ga: { text: 'উদ্দীপকের সুমন সাহেবের চরিত্রের সাথে ‘মমতাদি’ গল্পের লেখকের মায়ের মানবিক মূল্যবোধের সাদৃশ্য নিরূপণ কর।', marks: 3 },
              gha: { text: '“মহৎ কাজের পথে বাধা এলেও সুমন সাহেবের অবিচল মনোভাবই গল্পের মূল সুর”—উক্তিটির যথার্থতা মূল্যায়ন কর।', marks: 4 },
            },
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '1.0.0',
  },

  // 2. Cambridge / Edexcel O & A Level Structured Style
  {
    id: 'template-cambridge-edexcel',
    title: '২. Cambridge / Edexcel Structured Exam (O/A Level)',
    templateCategory: 'cambridge-edexcel',
    header: {
      instituteName: '',
      subInstituteText: 'International General Certificate of Secondary Education',
      examName: 'Mock Examination — Session 2026',
      sessionYear: '2026',
      subjectName: 'Physics (Theory Extended)',
      subjectCode: '0625/42',
      gradeClass: 'Year 11 / Grade 10',
      timeAllowed: '1 Hour 15 Minutes',
      totalMarks: '80',
      specialInstructions: 'Candidates answer on the Question Paper. No Additional Materials are required. Write your Centre number, candidate number and name in the spaces at the top of this page.',
      bismillahHeader: false,
      examSet: 'Paper 4',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'english',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'cambridge-grid',
      fontSize: 'md',
      lineSpacing: 'relaxed',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.06,
      watermarkType: 'text',
      showBorder: false,
      borderStyle: 'none',
      showHeaderCutLine: false,
      showOMRGrid: false,
      studentInfoBox: true,
      marksPosition: 'right-bracket',
      numberingStyle: 'english',
      showDottedAnswerLines: true,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'english',
      marginSize: 'standard',
    },
    sections: [
      {
        sectionId: 'sec-cambridge-p4',
        title: 'Structured Questions',
        subTitle: 'Answer all questions in the spaces provided.',
        marksInstruction: '[Total: 80 Marks]',
        questions: [
          {
            id: 'q-cam-1',
            type: 'short',
            qNumber: '1',
            stimulus: 'A car of mass 1200 kg travels along a straight, horizontal road at a constant speed of 25 m/s.',
            questionText: '(a) Calculate the kinetic energy of the car.\n(b) The driver applies the brakes to stop the car in 4.0 seconds. Determine the deceleration.',
            marks: 6,
            dottedLinesCount: 4,
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '1.0.0',
  },

  // 3. CBSE / ICSE School Examination Style
  {
    id: 'template-cbse-icse',
    title: '৩. CBSE / ICSE Standard Examination Format',
    templateCategory: 'cbse-icse',
    header: {
      instituteName: '',
      subInstituteText: 'All India Secondary School Examination',
      examName: 'Annual Board Assessment',
      sessionYear: '2026',
      subjectName: 'Mathematics (Standard)',
      subjectCode: '041',
      gradeClass: 'Class X',
      timeAllowed: '3 Hours',
      totalMarks: '80',
      specialInstructions: 'General Instructions:\n1. This question paper contains 38 questions divided into 5 Sections A, B, C, D and E.\n2. Section A comprises 20 MCQs of 1 mark each.\n3. Section B comprises 5 Short Answer Type-I questions of 2 marks each.\n4. Section C comprises 6 Short Answer Type-II questions of 3 marks each.',
      bismillahHeader: false,
      examSet: 'Set 1 (Code: 30/1/1)',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'english',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'modern-dual',
      fontSize: 'md',
      lineSpacing: 'normal',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.05,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'solid',
      showHeaderCutLine: false,
      showOMRGrid: false,
      studentInfoBox: true,
      marksPosition: 'right-bracket',
      numberingStyle: 'english',
      showDottedAnswerLines: false,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'english',
      marginSize: 'standard',
    },
    sections: [
      {
        sectionId: 'sec-cbse-a',
        title: 'SECTION A (20 Marks)',
        subTitle: 'Questions 1 to 20 carry 1 mark each.',
        marksInstruction: '[20 × 1 = 20]',
        questions: [
          {
            id: 'q-cbse-mcq-1',
            type: 'mcq',
            qNumber: '1',
            questionText: 'If two positive integers a and b are written as a = x³y² and b = xy³, where x, y are prime numbers, then HCF(a, b) is:',
            marks: 1,
            mcqOptions: ['xy', 'xy²', 'x³y³', 'x²y²'],
            mcqCorrectIndex: 1,
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '1.0.0',
  },

  // 4. Madrasah Board / Dakhil Arabic RTL Format
  {
    id: 'template-madrasah-dakhil',
    title: '৪. মাদরাসা শিক্ষা বোর্ড ও আরবি প্রশ্নপত্র (Dakhil / Kamil RTL)',
    templateCategory: 'madrasah-board',
    header: {
      instituteName: '',
      subInstituteText: 'বাংলাদেশ মাদরাসা শিক্ষা বোর্ড',
      examName: 'দাখিল নির্বাচনী পরীক্ষা',
      sessionYear: '২০২৬',
      subjectName: 'আল-কুরআন মাজিদ ও তাজভিদ',
      subjectCode: '১১২',
      gradeClass: 'দাখিল দশম শ্রেণি',
      timeAllowed: '২ ঘণ্টা ৩০ মিনিট',
      totalMarks: '৭০',
      specialInstructions: '[بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ — ملاحظة: اكتب الإجابة باللغة العربية أو البنغالية بصورة واضحة]',
      bismillahHeader: true,
      bismillahArabicText: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
      examSet: 'ক-সেট',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'bengali',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'madrasah-ornate',
      fontSize: 'md',
      lineSpacing: 'normal',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.08,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'double',
      showHeaderCutLine: false,
      showOMRGrid: false,
      studentInfoBox: false,
      marksPosition: 'right-bracket',
      numberingStyle: 'bengali',
      showDottedAnswerLines: false,
      isRTL: true,
      headerArabicBismillah: true,
      showTeacherNotes: false,
      pageNumberingFormat: 'bengali',
      marginSize: 'standard',
    },
    sections: [
      {
        sectionId: 'sec-quran-ayat',
        title: 'القسم الأول : النصوص القرآنية والتفسير (ক-বিভাগ : কুরআন ও তাফসির)',
        subTitle: 'যেকোনো ৩টি সৃজনশীল প্রশ্নের উত্তর দাও',
        marksInstruction: '[৩ × ১০ = ৩০]',
        isRTL: true,
        questions: [
          {
            id: 'q-madrasah-1',
            type: 'cq',
            qNumber: '১',
            isRTL: true,
            stimulus:
              'قَالَ اللَّهُ تَعَالَى: ﴿يَا أَيُّهَا الَّذِينَ آمَنُوا كُتِبَ عَلَيْكُمُ الصِّيَامُ كَمَا كُتِبَ عَلَى الَّذِينَ مِن قَبْلِكُمْ لَعَلَّكُمْ تَتَّقُونَ ۝ أَيَّامًا مَّعْدُودَاتٍ﴾ [سورة البقرة: ١٨٣-١٨৪]\n\nউদ্দীপক: জনাব রাশেদ একজন নিষ্ঠাবান ব্যবসায়ী। তিনি রমজান মাসে রোজা পালন করেন এবং গরিবদের মধ্যে উদারভাবে দান-সদকা করেন।',
            questionText: 'উদ্ধৃত আয়াত ও উদ্দীপক পড়ে নিচের প্রশ্নগুলোর উত্তর দাও:',
            marks: 10,
            cqParts: {
              ka: { text: '‘الصِّيَامُ’ শব্দের আভিধানিক অর্থ কী?', marks: 1 },
              kha: { text: '‘لَعَلَّكُمْ تَتَّقُونَ’—উদ্ধৃত বাক্যংশের মর্মার্থ বুঝিয়ে লেখ।', marks: 2 },
              ga: { text: 'জনাব রাশেদের কর্মকাণ্ডে উপর্যুক্ত আয়াতের কোন প্রধান লক্ষ্য বাস্তবায়িত হয়েছে? ব্যাখ্যা কর।', marks: 3 },
              gha: { text: '“সিয়াম সাধনা ব্যক্তি ও সমাজ জীবনে তাকওয়া প্রতিষ্ঠার শ্রেষ্ঠ মাধ্যম”—আয়াত ও উদ্দীপকের আলোকে মূল্যায়ন কর।', marks: 4 },
            },
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '1.0.0',
  },

  // 5. OMR 100-Question MCQ Speed Test Format
  {
    id: 'template-mcq-omr-speed',
    title: '৫. বহুনির্বাচনী ও অপটিক্যাল ওএমআর ফরম্যাট (2-Column MCQ Print)',
    templateCategory: 'nctb-general',
    header: {
      instituteName: '',
      subInstituteText: 'বহুনির্বাচনী অভীক্ষা (MCQ Examination)',
      examName: 'নির্বাচনী পরীক্ষা — বহুনির্বাচনী অভীক্ষা',
      sessionYear: '২০২৬',
      subjectName: 'সাধারণ বিজ্ঞান ও গণিত',
      subjectCode: '১২৭',
      gradeClass: 'দশম শ্রেণি',
      timeAllowed: '২৫ মিনিট',
      totalMarks: '২৫',
      specialInstructions: '[বিশেষ দ্রষ্টব্য: সরবরাহকৃত ওএমআর শিটে সঠিক উত্তরের বৃত্তটি কালো বলপয়েন্ট কলম দ্বারা ভরাট কর। প্রতিটি প্রশ্নের মান ১।]',
      bismillahHeader: false,
      examSet: 'ক-সেট',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'bengali',
      pageFormat: 'A4',
      columnLayout: 'two-column',
      headerStyle: 'classic-center',
      fontSize: 'compact',
      lineSpacing: 'tight',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.06,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'solid',
      showHeaderCutLine: true,
      showOMRGrid: true,
      studentInfoBox: true,
      marksPosition: 'hidden',
      numberingStyle: 'bengali',
      showDottedAnswerLines: false,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'bengali',
      marginSize: 'compact',
    },
    sections: [
      {
        sectionId: 'sec-mcq-speed-1',
        title: 'বহুনির্বাচনী প্রশ্নাবলি',
        subTitle: 'সকল প্রশ্নের উত্তর দাও',
        marksInstruction: '[২৫ × ১ = ২৫]',
        questions: [
          {
            id: 'q-mcq-1',
            type: 'mcq',
            qNumber: '১',
            questionText: 'বস্তুর জড়তা নিচের কোনটির ওপর নির্ভর করে?',
            marks: 1,
            mcqOptions: ['বেগ', 'ভর', 'ত্বরণ', 'বল'],
            mcqCorrectIndex: 1,
          },
          {
            id: 'q-mcq-2',
            type: 'mcq',
            qNumber: '২',
            questionText: 'কাজের পরম একক কোনটি?',
            marks: 1,
            mcqOptions: ['জুল (Joule)', 'ওয়াট (Watt)', 'নিউটন (Newton)', 'প্যাসকেল (Pascal)'],
            mcqCorrectIndex: 0,
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '1.0.0',
  },

  // 6. Primary & Kindergarten Illustrated Worksheet
  {
    id: 'template-primary-worksheet',
    title: '৬. প্রাথমিক ও কিন্ডারগার্টেন ওয়ার্কশিট (Primary / KG Illustrated)',
    templateCategory: 'primary-worksheet',
    header: {
      instituteName: '',
      subInstituteText: 'প্রাথমিক মূল্যায়ন পরীক্ষা',
      examName: 'শ্রেণি মূল্যায়ন ও বর্ণমালা পরীক্ষা',
      sessionYear: '২০২৬',
      subjectName: 'আমার বাংলা বই ও ছবি আঁকা',
      subjectCode: '০১',
      gradeClass: 'শিশু শ্রেণি / প্রথম শ্রেণি',
      timeAllowed: '১ ঘণ্টা',
      totalMarks: '৫০',
      specialInstructions: 'পরিষ্কার ও সুন্দর হাতের লেখায় উত্তর দাও। ছবি দেখে ফাঁকা ঘরে সঠিক বর্ণ বসাও।',
      bismillahHeader: false,
      examSet: '',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'bengali',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'modern-dual',
      fontSize: 'xl',
      lineSpacing: 'spacious',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.05,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'double',
      showHeaderCutLine: false,
      showOMRGrid: false,
      studentInfoBox: true,
      marksPosition: 'right-bracket',
      numberingStyle: 'parentheses-bengali',
      showDottedAnswerLines: true,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'bengali',
      marginSize: 'wide',
    },
    sections: [
      {
        sectionId: 'sec-primary-1',
        title: '১. সুন্দর করে লেখ ও দাগ টানো',
        subTitle: 'প্রতিটি প্রশ্নের উত্তর ডটেড লাইনে লেখ',
        marksInstruction: '[১০ নম্বর]',
        questions: [
          {
            id: 'q-kg-1',
            type: 'worksheet-trace',
            qNumber: '(১)',
            questionText: 'স্বরবর্ণ কয়টি ও কী কী? ডট লাইনে সুন্দর করে লেখ:',
            marks: 5,
            dottedLinesCount: 3,
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '1.0.0',
  },

  // 7. University / College Semester Final Exam
  {
    id: 'template-university-final',
    title: '৭. বিশ্ববিদ্যালয় ও সেমিস্টার ফাইনাল পরীক্ষা (University / College)',
    templateCategory: 'university-final',
    header: {
      instituteName: '',
      subInstituteText: 'Department of Computer Science & Engineering',
      examName: 'Semester Final Examination — Spring 2026',
      sessionYear: '2026',
      subjectName: 'Data Structures and Algorithms',
      subjectCode: 'CSE-2101',
      gradeClass: 'B.Sc. in CSE (4th Semester)',
      timeAllowed: '3 Hours',
      totalMarks: '60',
      specialInstructions: 'Answer any 5 (Five) questions out of 8. All questions carry equal marks. Figures in the right margin indicate full marks.',
      bismillahHeader: false,
      departmentName: 'Department of CSE',
      courseCode: 'CSE-2101',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'english',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'minimal-left',
      fontSize: 'md',
      lineSpacing: 'normal',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.05,
      watermarkType: 'text',
      showBorder: false,
      borderStyle: 'none',
      showHeaderCutLine: false,
      showOMRGrid: false,
      studentInfoBox: false,
      marksPosition: 'right-bracket',
      numberingStyle: 'q-prefix',
      showDottedAnswerLines: false,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'english',
      marginSize: 'standard',
    },
    sections: [
      {
        sectionId: 'sec-uni-core',
        title: 'Core Algorithm Problems',
        subTitle: 'Answer any 5 questions.',
        marksInstruction: '[5 × 12 = 60 Marks]',
        questions: [
          {
            id: 'q-uni-1',
            type: 'descriptive',
            qNumber: 'Q-1',
            questionText: '(a) Explain the difference between AVL Tree and Red-Black Tree in terms of rotation complexity.\n(b) Construct an AVL tree by inserting the elements: 15, 20, 24, 10, 13, 7, 30, 36, 25 sequentially.',
            marks: 12,
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '1.0.0',
  },

  // 8. Weekly Class Test / Pop Quiz Slip (2-Per-Page)
  {
    id: 'template-class-test-slip',
    title: '৮. সাপ্তাহিক ক্লাস টেস্ট ও কুইজ স্লিপ (Class Test Slip)',
    templateCategory: 'class-test-slip',
    header: {
      instituteName: '',
      subInstituteText: 'সাপ্তাহিক মূল্যায়ন টেস্ট (Weekly Assessment)',
      examName: 'ক্লাস টেস্ট — ০১',
      sessionYear: '২০২৬',
      subjectName: 'ইংরেজি ও সাধারণ গণিত',
      subjectCode: 'CT-01',
      gradeClass: 'অষ্টম শ্রেণি',
      timeAllowed: '২০ মিনিট',
      totalMarks: '২০',
      specialInstructions: 'সঠিক উত্তরের পাশে টিক (✓) দাও অথবা সংক্ষিপ্ত উত্তর লেখ।',
      bismillahHeader: false,
      examSet: '',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'bengali',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'modern-dual',
      fontSize: 'sm',
      lineSpacing: 'tight',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.05,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'dashed',
      showHeaderCutLine: true,
      showOMRGrid: false,
      studentInfoBox: true,
      marksPosition: 'right-bracket',
      numberingStyle: 'bengali',
      showDottedAnswerLines: true,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'none',
      marginSize: 'compact',
    },
    sections: [
      {
        sectionId: 'sec-ct-1',
        title: 'সংক্ষিপ্ত কুইজ প্রশ্নাবলি',
        subTitle: 'সকল প্রশ্নের উত্তর আবশ্যক',
        marksInstruction: '[২০ নম্বর]',
        questions: [
          {
            id: 'q-ct-1',
            type: 'short',
            qNumber: '১',
            questionText: 'বৃত্তের পরিধি ও ব্যাসের অনুপাতকে কী বলা হয়?',
            marks: 2,
            dottedLinesCount: 2,
          },
          {
            id: 'q-ct-2',
            type: 'mcq',
            qNumber: '২',
            questionText: 'He is ______ honest man. (Fill in with article)',
            marks: 2,
            mcqOptions: ['a', 'an', 'the', 'no article'],
            mcqCorrectIndex: 1,
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '1.0.0',
  },

  // 9. NCTB English 1st Paper — Seen/Unseen, MCQ, Flow Chart, Summary
  {
    id: 'template-nctb-english-1st',
    title: '৯. English 1st Paper — Seen/Unseen & Info Transfer (NCTB)',
    templateCategory: 'nctb-english',
    header: {
      instituteName: '',
      subInstituteText: 'Board Standard — English First Paper',
      examName: 'Half-Yearly Examination',
      sessionYear: '২০২৬',
      subjectName: 'English 1st Paper',
      subjectCode: '107',
      gradeClass: 'নবম-দশম শ্রেণি',
      timeAllowed: '3 Hours',
      totalMarks: '100',
      specialInstructions: 'Part-A: Reading Test (50) — Seen, Unseen & Vocabulary. Part-B: Writing Test (50). Figures in margin indicate full marks.',
      bismillahHeader: false,
      examSet: 'Set-A',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'english',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'classic-center',
      fontSize: 'md',
      lineSpacing: 'normal',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.05,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'solid',
      showHeaderCutLine: false,
      showOMRGrid: false,
      studentInfoBox: true,
      marksPosition: 'right-bracket',
      numberingStyle: 'english',
      showDottedAnswerLines: false,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'english',
      marginSize: 'standard',
    },
    sections: [
      {
        sectionId: 'sec-eng1-seen',
        title: 'Part-A : Reading Test — Seen Comprehension',
        subTitle: 'Read the passage and answer Q 1-4',
        marksInstruction: '[Seen: 25 Marks]',
        questions: [
          {
            id: 'q-eng1-passage',
            type: 'passage',
            qNumber: '1',
            stimulus: 'May Day or International Workers’ Day is observed on May 1 all over the world. It commemorates the historic struggle of working people to establish an 8-hour workday. In 1886, workers in Chicago demanded this right and many sacrificed their lives.',
            questionText: 'A. Choose the correct answer from the alternatives:',
            marks: 5,
            mcqOptions: ['May Day is observed on — (a) 1 May (b) 1 June (c) 8 March (d) 26 March', 'Workers demanded — (a) 6 hours (b) 8 hours (c) 10 hours (d) 12 hours', 'In 1886 the movement took place in — (a) London (b) Chicago (c) Dhaka (d) Paris', 'The day commemorates — (a) victory (b) struggle (c) festival (d) holiday', 'The workers sacrificed their — (a) money (b) time (c) lives (d) jobs'],
          },
          {
            id: 'q-eng1-flowchart',
            type: 'short',
            qNumber: '2',
            questionText: 'Make a flow chart showing the background of May Day movement. (One is done for you: 1. Workers exploited → 2. ____ → 3. ____ → 4. ____ → 5. ____ → 6. International recognition)',
            marks: 5,
            dottedLinesCount: 3,
          },
        ],
      },
      {
        sectionId: 'sec-eng1-unseen',
        title: 'Part-A : Unseen — Summary & Gap Fill',
        subTitle: 'Read the unseen passage and answer Q 5-6',
        marksInstruction: '[15 Marks]',
        questions: [
          {
            id: 'q-eng1-summary',
            type: 'descriptive',
            qNumber: '5',
            questionText: 'Summarize the unseen passage in your own words within 90-100 words.',
            marks: 10,
            dottedLinesCount: 6,
          },
          {
            id: 'q-eng1-cloze',
            type: 'fill-blanks',
            qNumber: '6',
            questionText: 'Fill in the blanks with suitable words from the box:',
            marks: 5,
            fillBlanksOptions: ['struggle', 'sacrifice', 'establish', 'demand', 'observe', 'commemorate', 'historic', 'international'],
            subQuestions: [
              { id: 'sq-6a', label: '(a)', text: 'We ______ May Day every year.', marks: 1 },
              { id: 'sq-6b', label: '(b)', text: 'Workers ______ an 8-hour day.', marks: 1 },
            ],
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '2.0.0',
  },

  // 10. NCTB English 2nd Paper — Grammar & Composition
  {
    id: 'template-nctb-english-2nd',
    title: '১০. English 2nd Paper — Grammar & Writing (NCTB)',
    templateCategory: 'nctb-english',
    header: {
      instituteName: '',
      subInstituteText: 'Board Standard — English Second Paper',
      examName: 'Annual Examination',
      sessionYear: '২০২৬',
      subjectName: 'English 2nd Paper',
      subjectCode: '108',
      gradeClass: 'নবম-দশম শ্রেণি',
      timeAllowed: '3 Hours',
      totalMarks: '100',
      specialInstructions: 'Part-A: Grammar (60) — Answer all. Part-B: Composition (40). No extra sheet will be provided.',
      bismillahHeader: false,
      examSet: 'Set-A',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'english',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'classic-center',
      fontSize: 'md',
      lineSpacing: 'normal',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.05,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'solid',
      showHeaderCutLine: false,
      showOMRGrid: false,
      studentInfoBox: true,
      marksPosition: 'right-bracket',
      numberingStyle: 'english',
      showDottedAnswerLines: false,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'english',
      marginSize: 'standard',
    },
    sections: [
      {
        sectionId: 'sec-eng2-grammar',
        title: 'Part-A : Grammar (60 Marks)',
        subTitle: 'Answer all questions',
        marksInstruction: '[60 Marks]',
        questions: [
          {
            id: 'q-eng2-gap',
            type: 'grammar-cloze',
            qNumber: '1',
            questionText: 'Fill in the blanks with suitable prepositions/articles:',
            marks: 5,
            subQuestions: [
              { id: 'sq-1a', label: '(a)', text: 'He is fond ______ sweets.', marks: 1 },
              { id: 'sq-1b', label: '(b)', text: '______ honest man respects truth.', marks: 1 },
            ],
          },
          {
            id: 'q-eng2-transform',
            type: 'grammar-cloze',
            qNumber: '2',
            questionText: 'Transform the sentences as directed:',
            marks: 5,
            subQuestions: [
              { id: 'sq-2a', label: '(a)', text: 'He is the best boy in the class. (Negative)', marks: 1 },
              { id: 'sq-2b', label: '(b)', text: 'Though he is poor, he is honest. (Compound)', marks: 1 },
            ],
          },
          {
            id: 'q-eng2-suffix',
            type: 'fill-blanks',
            qNumber: '3',
            questionText: 'Complete the text with suitable suffix/prefix:',
            marks: 5,
            fillBlanksOptions: ['honest', 'wise', 'act', 'success', 'beauty', 'care', 'danger', 'create'],
          },
        ],
      },
      {
        sectionId: 'sec-eng2-composition',
        title: 'Part-B : Composition (40 Marks)',
        subTitle: 'Attempt all',
        marksInstruction: '[40 Marks]',
        questions: [
          {
            id: 'q-eng2-paragraph',
            type: 'descriptive',
            qNumber: '8',
            questionText: 'Write a paragraph on “A Winter Morning” within 150 words.',
            marks: 10,
            dottedLinesCount: 6,
          },
          {
            id: 'q-eng2-letter',
            type: 'descriptive',
            qNumber: '9',
            questionText: 'Write a letter to your friend inviting him to visit your village during the winter vacation.',
            marks: 10,
            dottedLinesCount: 6,
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '2.0.0',
  },

  // 11. NCTB Mathematics — CQ with OR Alternative (Geometry/Algebra)
  {
    id: 'template-nctb-math-cq',
    title: '১১. গণিত — সৃজনশীল ও বিকল্প (NCTB Math CQ with OR)',
    templateCategory: 'nctb-math',
    header: {
      instituteName: '',
      subInstituteText: 'গণিত — সৃজনশীল (আবশ্যিক)',
      examName: 'নির্বাচনী পরীক্ষা',
      sessionYear: '২০২৬',
      subjectName: 'সাধারণ গণিত',
      subjectCode: '১০৯',
      gradeClass: 'দশম শ্রেণি',
      timeAllowed: '২ ঘণ্টা ৩০ মিনিট',
      totalMarks: '৭০',
      specialInstructions: '[প্রতিটি বিভাগ থেকে কমপক্ষে ১টি করে মোট ৭টি প্রশ্নের উত্তর দাও। প্রয়োজনে জ্যামিতিক চিত্র আঁকতে পারো।]',
      bismillahHeader: false,
      examSet: 'ক-সেট',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'bengali',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'classic-center',
      fontSize: 'md',
      lineSpacing: 'normal',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.05,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'solid',
      showHeaderCutLine: false,
      showOMRGrid: false,
      studentInfoBox: false,
      marksPosition: 'right-bracket',
      numberingStyle: 'bengali',
      showDottedAnswerLines: false,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'bengali',
      marginSize: 'standard',
    },
    sections: [
      {
        sectionId: 'sec-math-ka',
        title: 'ক-বিভাগ : বীজগণিত',
        subTitle: 'যেকোনো ২টি প্রশ্নের উত্তর দাও',
        marksInstruction: '[২ × ১০ = ২০]',
        questions: [
          {
            id: 'q-math-1',
            type: 'cq',
            qNumber: '১',
            stimulus: 'U = {1,2,3,4,5,6,7}, A = {1,2,3}, B = {2,4,6} এবং C = {3,4,5}',
            questionText: 'উদ্দীপকের আলোকে প্রশ্নগুলোর উত্তর দাও:',
            marks: 10,
            cqParts: {
              ka: { text: 'P(A ∩ B) নির্ণয় কর।', marks: 1 },
              kha: { text: 'দেখাও যে, (A ∪ B)′ = A′ ∩ B′', marks: 3 },
              ga: { text: 'যদি f(x)= (x²-1)/(x+1) হয়, তবে প্রমাণ কর f(A) ⊆ U', marks: 3 },
              gha: { text: 'উদ্দীপকের আলোকে ভেনচিত্র অঙ্কন করে (A−B) ∪ C নির্ণয় কর।', marks: 3 },
            },
            orAlternative: {
              questionText: 'অথবা, x = √3+√2 হলে, (x⁴+1/x⁴) এর মান নির্ণয় কর এবং প্রমাণ কর x³+1/x³ = 18√3',
            },
          },
        ],
      },
      {
        sectionId: 'sec-math-kha',
        title: 'খ-বিভাগ : জ্যামিতি',
        subTitle: 'যেকোনো ২টি প্রশ্নের উত্তর দাও',
        marksInstruction: '[২ × ১০ = ২০]',
        questions: [
          {
            id: 'q-math-geo-1',
            type: 'math-proof',
            qNumber: '৪',
            stimulus: '△ABC এ AB = AC এবং D, BC এর মধ্যবিন্দু।',
            questionText: 'প্রমাণ কর যে, △ABD ≅ △ACD এবং AD ⊥ BC',
            marks: 10,
            stimulusImage: { url: '', caption: 'চিত্র: সমদ্বিবাহু ত্রিভুজ', position: 'center', widthPercent: 40 },
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '2.0.0',
  },

  // 12. NCTB General Science / ICT — Diagram + Matching + Fill Blanks
  {
    id: 'template-nctb-science-ict',
    title: '১২. বিজ্ঞান / ICT — চিত্র, মিলকরণ ও শূন্যস্থান (NCTB Science/ICT)',
    templateCategory: 'nctb-general',
    header: {
      instituteName: '',
      subInstituteText: 'বিজ্ঞান ও তথ্য প্রযুক্তি',
      examName: 'অর্ধ-বার্ষিক পরীক্ষা',
      sessionYear: '২০২৬',
      subjectName: 'তথ্য ও যোগাযোগ প্রযুক্তি',
      subjectCode: '154',
      gradeClass: 'অষ্টম শ্রেণি',
      timeAllowed: '২ ঘণ্টা',
      totalMarks: '50',
      specialInstructions: '১-১০ MCQ, ১১-১৫ সংক্ষিপ্ত, ১৬-১৮ রচনামূলক ও ICT ডায়াগ্রাম। চিত্র প্রয়োজনে পেন্সিলে আঁকো।',
      bismillahHeader: false,
      examSet: 'ক-সেট',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'bengali',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'classic-center',
      fontSize: 'md',
      lineSpacing: 'normal',
      showWatermark: false,
      watermarkText: '',
      watermarkOpacity: 0.05,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'solid',
      showHeaderCutLine: false,
      showOMRGrid: false,
      studentInfoBox: true,
      marksPosition: 'right-bracket',
      numberingStyle: 'bengali',
      showDottedAnswerLines: false,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'bengali',
      marginSize: 'standard',
    },
    sections: [
      {
        sectionId: 'sec-ict-mcq',
        title: 'ক-বিভাগ : বহুনির্বাচনী',
        subTitle: 'সকল প্রশ্নের উত্তর দাও',
        marksInstruction: '[১০ × ১ = ১০]',
        questions: [
          {
            id: 'q-ict-mcq-1',
            type: 'mcq',
            qNumber: '১',
            questionText: 'কম্পিউটারের মস্তিষ্ক বলা হয় কোনটিকে?',
            marks: 1,
            mcqOptions: ['মনিটর', 'CPU', 'RAM', 'HDD'],
            mcqCorrectIndex: 1,
          },
        ],
      },
      {
        sectionId: 'sec-ict-matching',
        title: 'খ-বিভাগ : মিলকরণ ও শূন্যস্থান',
        subTitle: 'নির্দেশনা অনুযায়ী উত্তর দাও',
        marksInstruction: '[১০ নম্বর]',
        questions: [
          {
            id: 'q-ict-matching-1',
            type: 'matching',
            qNumber: '১১',
            questionText: 'বাম কলামের সাথে ডান কলাম মিল কর:',
            marks: 5,
            matchingColumns: { left: ['CPU', 'RAM', 'HDD', 'GPU'], right: ['গ্রাফিক্স', 'স্থায়ী মেমোরি', 'অস্থায়ী মেমোরি', 'প্রসেসর'] },
          },
          {
            id: 'q-ict-fill-1',
            type: 'fill-blanks',
            qNumber: '১২',
            questionText: 'শূন্যস্থান পূরণ কর (Clue Box থেকে):',
            marks: 5,
            fillBlanksOptions: ['Binary', 'Algorithm', 'Flowchart', 'Compiler', 'Internet', 'Protocol'],
            subQuestions: [
              { id: 'sq-12a', label: '(a)', text: 'কম্পিউটার ______ সংখ্যা পদ্ধতিতে কাজ করে।', marks: 1 },
              { id: 'sq-12b', label: '(b)', text: 'সমস্যা সমাধানের ধাপকে ______ বলে।', marks: 1 },
            ],
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '2.0.0',
  },

  // 13. PSC / Primary Scholarship (Class 5 Board)
  {
    id: 'template-psc-scholarship',
    title: '১৩. প্রাথমিক বৃত্তি ও সমাপনী (Class 5 PSC / Scholarship)',
    templateCategory: 'primary-worksheet',
    header: {
      instituteName: '',
      subInstituteText: 'প্রাথমিক শিক্ষা সমাপনী / বৃত্তি পরীক্ষা',
      examName: 'বৃত্তি পরীক্ষা — মডেল টেস্ট',
      sessionYear: '২০২৬',
      subjectName: 'বাংলা ও ইংরেজি',
      subjectCode: 'PSC-01',
      gradeClass: 'পঞ্চম শ্রেণি',
      timeAllowed: '২ ঘণ্টা ৩০ মিনিট',
      totalMarks: '100',
      specialInstructions: '১. সকল প্রশ্নের উত্তর দিতে হবে। ২. ডান পাশের সংখ্যা পূর্ণমান নির্দেশ করে। ৩. সুন্দর হাতের লেখায় উত্তর দাও।',
      bismillahHeader: false,
      examSet: 'ক-সেট',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'bengali',
      pageFormat: 'A4',
      columnLayout: 'single',
      headerStyle: 'classic-center',
      fontSize: 'md',
      lineSpacing: 'normal',
      showWatermark: true,
      watermarkText: 'বৃত্তি পরীক্ষা ২০২৬',
      watermarkOpacity: 0.06,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'double',
      showHeaderCutLine: true,
      showOMRGrid: false,
      studentInfoBox: true,
      marksPosition: 'right-bracket',
      numberingStyle: 'bengali',
      showDottedAnswerLines: false,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'bengali',
      marginSize: 'standard',
    },
    sections: [
      {
        sectionId: 'sec-psc-bangla',
        title: 'ক-বিভাগ : বাংলা (৪০ নম্বর)',
        subTitle: 'সকল প্রশ্নের উত্তর দাও',
        marksInstruction: '[৪০]',
        questions: [
          {
            id: 'q-psc-bn-1',
            type: 'cq',
            qNumber: '১',
            stimulus: 'সততার পুরস্কার গল্প থেকে: “মহৎ মানুষেরা সবসময় সত্য কথা বলেন।”',
            questionText: 'উদ্দীপক পড়ে প্রশ্নগুলোর উত্তর দাও:',
            marks: 10,
            cqParts: {
              ka: { text: 'সততার সংজ্ঞা দাও।', marks: 1 },
              kha: { text: 'সত্যবাদিতার দুটি উপকারিতা লেখ।', marks: 2 },
              ga: { text: 'গল্পের মূলভাব নিজের ভাষায় লেখ।', marks: 3 },
              gha: { text: 'তুমি কীভাবে সৎ জীবন গঠন করবে— আলোচনা কর।', marks: 4 },
            },
          },
        ],
      },
      {
        sectionId: 'sec-psc-eng',
        title: 'খ-বিভাগ : English (40 Marks)',
        subTitle: 'Answer all questions',
        marksInstruction: '[40 Marks]',
        questions: [
          {
            id: 'q-psc-eng-1',
            type: 'passage',
            qNumber: '4',
            stimulus: 'My mother is the best teacher of my life. She teaches me honesty and kindness.',
            questionText: 'Read the passage and answer:',
            marks: 5,
            subQuestions: [
              { id: 'sq-psc-e1', label: 'a', text: 'Who is the best teacher?', marks: 1 },
              { id: 'sq-psc-e2', label: 'b', text: 'What does she teach?', marks: 2 },
            ],
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '2.0.0',
  },

  // 14. Admission Model Test — 100 MCQ Time-Pressure (Varsity/Medical)
  {
    id: 'template-admission-model',
    title: '১৪. ভর্তি মডেল টেস্ট — ১০০ MCQ (Varsity / Medical Admission)',
    templateCategory: 'nctb-general',
    header: {
      instituteName: '',
      subInstituteText: 'বিশ্ববিদ্যালয় ভর্তি মডেল টেস্ট',
      examName: 'মডেল টেস্ট — ০১ (Admission Standard)',
      sessionYear: '২০২৬',
      subjectName: 'বিজ্ঞান বিভাগ — পদার্থ, রসায়ন, জীববিজ্ঞান, ইংরেজি',
      subjectCode: 'ADM-100',
      gradeClass: 'HSC উত্তীর্ণ',
      timeAllowed: '60 Minutes',
      totalMarks: '100',
      specialInstructions: '• প্রতিটি সঠিক উত্তরে ১ নম্বর। • ভুল উত্তরে ০.২৫ নম্বর কাটা যাবে। • OMR শিটে বৃত্ত ভরাট কর। • ক্যালকুলেটর নিষিদ্ধ।',
      bismillahHeader: false,
      examSet: 'Set-A (Code: 101)',
    },
    layout: {
      fontBengali: 'hind',
      fontArabic: 'amiri',
      numeralSystem: 'english',
      pageFormat: 'A4',
      columnLayout: 'two-column',
      headerStyle: 'classic-center',
      fontSize: 'compact',
      lineSpacing: 'tight',
      showWatermark: true,
      watermarkText: 'ADMISSION MODEL TEST',
      watermarkOpacity: 0.06,
      watermarkType: 'text',
      showBorder: true,
      borderStyle: 'solid',
      showHeaderCutLine: true,
      showOMRGrid: true,
      studentInfoBox: true,
      marksPosition: 'hidden',
      numberingStyle: 'english',
      showDottedAnswerLines: false,
      isRTL: false,
      headerArabicBismillah: false,
      showTeacherNotes: false,
      pageNumberingFormat: 'english',
      marginSize: 'compact',
    },
    sections: [
      {
        sectionId: 'sec-adm-phy',
        title: 'Physics — 25 × 1 = 25',
        subTitle: 'Answer all',
        marksInstruction: '[Negative: -0.25 per wrong]',
        questions: [
          {
            id: 'q-adm-phy-1',
            type: 'mcq',
            qNumber: '1',
            questionText: 'Dimension of Planck constant (h) is:',
            marks: 1,
            mcqOptions: ['[ML²T⁻¹]', '[MLT⁻¹]', '[ML²T⁻²]', '[M⁰LT⁻¹]'],
            mcqCorrectIndex: 0,
          },
          {
            id: 'q-adm-phy-2',
            type: 'mcq-polynomial',
            qNumber: '2',
            questionText: 'Which statements are correct for projectile motion?',
            marks: 1,
            polynomialStatements: ['Horizontal velocity remains constant', 'Vertical acceleration is g downward', 'Range is max at 45° (without air resistance)'],
            polynomialQuestionText: 'Which is correct?',
            mcqOptions: ['i & ii', 'ii & iii', 'i & iii', 'i, ii & iii'],
            mcqCorrectIndex: 3,
          },
        ],
      },
      {
        sectionId: 'sec-adm-chem',
        title: 'Chemistry — 25 × 1 = 25',
        subTitle: 'Answer all',
        marksInstruction: '[25 Marks]',
        questions: [
          {
            id: 'q-adm-chem-1',
            type: 'mcq',
            qNumber: '26',
            questionText: 'pH of 0.01 M HCl solution is:',
            marks: 1,
            mcqOptions: ['1', '2', '3', '0.01'],
            mcqCorrectIndex: 1,
          },
        ],
      },
    ],
    lastModified: new Date().toISOString(),
    version: '2.0.0',
  },
];
