import { NextRequest } from "next/server";
import { z } from "zod";
import { requireApiAccess } from "@/lib/api-auth";
import { badRequest, handleApiError, successResponse } from "@/lib/api-response";
import { getNotificationConfig, saveNotificationConfig } from "@/lib/notifications";
import { NOTIFICATION_CHANNELS } from "@/lib/notifications/types";

const schema = z.object({ enabled: z.boolean(), events: z.record(z.boolean()), channels: z.array(z.enum(NOTIFICATION_CHANNELS)), fromEmail: z.string().email().optional(), fromName: z.string().optional(), resendApiKey: z.string().optional(), whatsappAccessToken: z.string().optional(), whatsappPhoneNumberId: z.string().optional(), smsApiUrl: z.string().url().optional(), smsApiKey: z.string().optional(), smsFrom: z.string().optional() });
export async function GET(request: NextRequest) { try { const access = await requireApiAccess(request, { module: "settings" }); if ("response" in access) return access.response; const { settings } = await getNotificationConfig(access.authContext.tenantId); return successResponse({ ...settings, resendApiKey: settings.resendApiKey ? "configured" : undefined, whatsappAccessToken: settings.whatsappAccessToken ? "configured" : undefined, smsApiKey: settings.smsApiKey ? "configured" : undefined }); } catch (error) { return handleApiError(error); } }
export async function PUT(request: NextRequest) { try { const access = await requireApiAccess(request, { module: "settings", action: "manage" }); if ("response" in access) return access.response; const parsed = schema.safeParse(await request.json()); if (!parsed.success) return badRequest("Invalid notification settings"); const current = await getNotificationConfig(access.authContext.tenantId); const secrets = ["resendApiKey", "whatsappAccessToken", "smsApiKey"] as const; const patch = { settings: { ...parsed.data } }; for (const key of secrets) if (parsed.data[key] === "configured" || !parsed.data[key]) (patch.settings as Record<string, unknown>)[key] = current.settings[key]; await saveNotificationConfig(access.authContext.tenantId, patch); return successResponse({ enabled: parsed.data.enabled, events: parsed.data.events, channels: parsed.data.channels }, "Notification settings updated"); } catch (error) { return handleApiError(error); } }
