import { NextRequest } from "next/server";
import { z } from "zod";
import { requireApiAccess } from "@/lib/api-auth";
import { badRequest, handleApiError, successResponse } from "@/lib/api-response";
import { getNotificationConfig, saveNotificationConfig } from "@/lib/notifications";
import { NOTIFICATION_CHANNELS } from "@/lib/notifications/types";

const templateSchema = z.object({ id: z.string().optional(), event: z.enum(["ABSENCE_ALERT", "FEE_REMINDER", "EXAM_RESULT_PUBLISHED", "EMERGENCY_BROADCAST"]), channel: z.enum(NOTIFICATION_CHANNELS), subject: z.string().optional(), body: z.string().min(1), enabled: z.boolean().default(true) });

export async function GET(request: NextRequest) { try { const access = await requireApiAccess(request, { module: "settings" }); if ("response" in access) return access.response; const config = await getNotificationConfig(access.authContext.tenantId); return successResponse({ settings: { ...config.settings, resendApiKey: config.settings.resendApiKey ? "configured" : undefined, whatsappAccessToken: config.settings.whatsappAccessToken ? "configured" : undefined, smsApiKey: config.settings.smsApiKey ? "configured" : undefined }, templates: config.templates }); } catch (error) { return handleApiError(error); } }

export async function POST(request: NextRequest) { try { const access = await requireApiAccess(request, { module: "settings", action: "manage" }); if ("response" in access) return access.response; const parsed = templateSchema.omit({ id: true }).safeParse(await request.json()); if (!parsed.success) return badRequest("Invalid notification template"); const now = new Date().toISOString(); const template = { ...parsed.data, id: crypto.randomUUID(), tenantId: access.authContext.tenantId, createdAt: now, updatedAt: now }; await saveNotificationConfig(access.authContext.tenantId, { templates: [...(await getNotificationConfig(access.authContext.tenantId)).templates, template] }); return successResponse(template, "Template created", 201); } catch (error) { return handleApiError(error); } }

export async function PUT(request: NextRequest) { try { const access = await requireApiAccess(request, { module: "settings", action: "manage" }); if ("response" in access) return access.response; const parsed = templateSchema.required({ id: true }).safeParse(await request.json()); if (!parsed.success) return badRequest("Template id and valid fields are required"); const config = await getNotificationConfig(access.authContext.tenantId); const templates = config.templates.map((item) => item.id === parsed.data.id ? { ...item, ...parsed.data, updatedAt: new Date().toISOString(), tenantId: access.authContext.tenantId } : item); if (!templates.some((item) => item.id === parsed.data.id)) return badRequest("Template not found"); await saveNotificationConfig(access.authContext.tenantId, { templates }); return successResponse(templates.find((item) => item.id === parsed.data.id), "Template updated"); } catch (error) { return handleApiError(error); } }

export async function DELETE(request: NextRequest) { try { const access = await requireApiAccess(request, { module: "settings", action: "manage" }); if ("response" in access) return access.response; const id = new URL(request.url).searchParams.get("id"); if (!id) return badRequest("Template id is required"); const config = await getNotificationConfig(access.authContext.tenantId); await saveNotificationConfig(access.authContext.tenantId, { templates: config.templates.filter((item) => item.id !== id) }); return successResponse({ id }, "Template deleted"); } catch (error) { return handleApiError(error); } }
